<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClientFlow.Application\ClientFlow.Application.csproj" />
    <ProjectReference Include="..\ClientFlow.Domain\ClientFlow.Domain.csproj" />
  </ItemGroup>

</Project>
